apiVersion: v1
kind: Pod
metadata:
  name: zhoujinj-end2end-dgl
spec:
  nodeSelector:
    node.kubernetes.io/instance-type: p3.2xlarge # optional
  restartPolicy: Never
  containers:
    - name: benchmark
      image: public.ecr.aws/s1o7b3d9/asail-public-dev:pytorch1.9-cuda11.1-dgl0.7.0
      args:
        - "bash"
        - "-c"
        - |
          cd /root
          git clone https://github.com/dmlc/dgl.git
          cd dgl/examples/pytorch/gcn
          python train.py --dataset cora --self-loop --gpu 0
      resources:
        limits:              
          nvidia.com/gpu: "1"
